export const brandPalette = {
  ink: "#1f2a1f",
  muted: "#536151",
  moss: "#36543b",
  leaf: "#6c8a53",
  sun: "#f4c96b",
  clay: "#c86d4b",
  sage: "#dbe8d0",
  cream: "#faf6ec",
  paperTop: "#fdf8ef",
  paperBottom: "#f4efde",
  printPaperTop: "#f8f0dd",
  printPaperMiddle: "#fbf2e2",
  printPaperBottom: "#f0e4c9",
  creamBright: "#fffaf2",
  paperInverse: "#eef6e5",
  paperInverseStrong: "#f6fbef",
  grid: "#dfe8d1",
  sageBright: "#b7d498",
  leafBright: "#8daf68",
  sageLively: "#9bb881",
  sunDeep: "#d6a94d",
  clayDeep: "#b85a39",
  mossGradientTop: "#2f4734",
  mossGradientBottom: "#263a2a",
  mossPanelTop: "#39523c",
  mossPanelBottom: "#2f4331",
  logoGuide: "#c3d6b8",
};

export const logoMarkSettings = {
  rings: 4,
  innerRings: 2,
  firstRadius: 21.4,
  spacing: 13.6,
  outerSpacing: 12.6,
  circleRadius: 13.1,
  middleCircleRadius: 13.8,
  outerCircleRadius: 12.2,
  rotation: -54,
  ringTwist: -36,
  padding: 24,
  guideOpacity: 0,
  guideStroke: 1.5,
  showGuides: false,
  transparent: true,
  centerColor: brandPalette.moss,
  innerColor: brandPalette.sage,
  middleColor: brandPalette.leaf,
  outerColor: brandPalette.moss,
  guideColor: brandPalette.sage,
  backgroundColor: brandPalette.cream,
};

export const logoLabSettings = {
  ...logoMarkSettings,
  guideOpacity: 0.9,
  showGuides: true,
};

export const logoIntroConfig = {
  outputName: "number-garden-logo-intro",
  holdDuration: 0.8,
  backgroundColor: brandPalette.cream,
  initialGeometry: {
    construction: "linear",
    outerRadius: 85,
    circleRadius: 3.6,
    rotation: -90,
    ringTwist: 0,
  },
  finalGeometry: {
    rings: logoMarkSettings.rings,
    innerRings: logoMarkSettings.innerRings,
    rotation: logoMarkSettings.rotation,
    ringTwist: logoMarkSettings.ringTwist,
    firstRadius: logoMarkSettings.firstRadius,
    spacing: logoMarkSettings.spacing,
    outerSpacing: logoMarkSettings.outerSpacing,
    circleRadius: logoMarkSettings.circleRadius,
    middleCircleRadius: logoMarkSettings.middleCircleRadius,
    outerCircleRadius: logoMarkSettings.outerCircleRadius,
  },
  animation: {
    transitionDuration: 2.88,
    overshootScale: 1,
    guideOpacity: 0,
    startGuideOpacity: 0.68,
  },
  palette: {
    center: brandPalette.moss,
    inner: brandPalette.sage,
    middle: brandPalette.leaf,
    outer: brandPalette.moss,
    guide: brandPalette.logoGuide,
    wordmark: brandPalette.ink,
    tagline: brandPalette.muted,
  },
  text: {
    showWordmark: true,
    wordmark: "The Number Garden",
    tagline: "Joyful mathematics for curious minds",
    wordmarkDelay: 3.35,
    taglineDelay: 3.75,
    revealDuration: 0.715,
  },
};

export const publicPalette = {
  name: "The Number Garden",
  sources: {
    brandConfig: "/src/config/brand.js",
    siteCss: "/src/styles/brand.css",
    favicon: "/public/favicon.svg",
    logoMark: "/public/brand/logo-mark.svg",
  },
  core: {
    ink: brandPalette.ink.toUpperCase(),
    muted: brandPalette.muted.toUpperCase(),
    moss: brandPalette.moss.toUpperCase(),
    leaf: brandPalette.leaf.toUpperCase(),
    sun: brandPalette.sun.toUpperCase(),
    clay: brandPalette.clay.toUpperCase(),
    sage: brandPalette.sage.toUpperCase(),
    cream: brandPalette.cream.toUpperCase(),
  },
  supporting: {
    paperTop: brandPalette.paperTop.toUpperCase(),
    paperBottom: brandPalette.paperBottom.toUpperCase(),
    printPaperTop: brandPalette.printPaperTop.toUpperCase(),
    printPaperMiddle: brandPalette.printPaperMiddle.toUpperCase(),
    printPaperBottom: brandPalette.printPaperBottom.toUpperCase(),
    creamBright: brandPalette.creamBright.toUpperCase(),
    paperInverse: brandPalette.paperInverse.toUpperCase(),
    paperInverseStrong: brandPalette.paperInverseStrong.toUpperCase(),
    grid: brandPalette.grid.toUpperCase(),
    sageBright: brandPalette.sageBright.toUpperCase(),
    leafBright: brandPalette.leafBright.toUpperCase(),
    sageLively: brandPalette.sageLively.toUpperCase(),
    sunDeep: brandPalette.sunDeep.toUpperCase(),
    clayDeep: brandPalette.clayDeep.toUpperCase(),
    mossGradientTop: brandPalette.mossGradientTop.toUpperCase(),
    mossGradientBottom: brandPalette.mossGradientBottom.toUpperCase(),
    mossPanelTop: brandPalette.mossPanelTop.toUpperCase(),
    mossPanelBottom: brandPalette.mossPanelBottom.toUpperCase(),
  },
};
