/**
 * @typedef {"art" | "beauty" | "games" | "imagination" | "logic" | "patterns" | "play" | "poetry" | "proof" | "science"} QuoteTheme
 * @typedef {"verified" | "secondary" | "needs-review"} QuoteVerificationStatus
 * @typedef {object} MathQuote
 * @property {string} id
 * @property {string} text
 * @property {string} author
 * @property {string} [authorLifespan]
 * @property {string} [work]
 * @property {number} [year]
 * @property {string} [sourceUrl]
 * @property {string} [sourceLabel]
 * @property {string} sourceNote
 * @property {QuoteVerificationStatus} verificationStatus
 * @property {QuoteTheme[]} themes
 */

/** @type {MathQuote[]} */
export const mathArtQuotes = [
  {
    id: "carroll-symbolic-logic-mental-recreation",
    text: "Mental recreation is a thing that we all of us need for our mental health.",
    author: "Lewis Carroll",
    authorLifespan: "1832-1898",
    work: "Symbolic Logic",
    year: 1896,
    sourceUrl: "https://www.gutenberg.org/files/28696/28696-h/28696-h.htm",
    sourceLabel: "Project Gutenberg",
    sourceNote: "Carroll introduces symbolic logic alongside games such as backgammon, chess, and Halma.",
    verificationStatus: "verified",
    themes: ["games", "logic", "play"],
  },
  {
    id: "hardy-maker-of-patterns",
    text: "A mathematician, like a painter or poet, is a maker of patterns.",
    author: "G. H. Hardy",
    authorLifespan: "1877-1947",
    work: "A Mathematician's Apology",
    year: 1940,
    sourceUrl: "https://plus.maths.org/content/makers-patterns-mathematics-and-art",
    sourceLabel: "Plus Magazine",
    sourceNote: "A canonical math-as-art quotation from Hardy's essay.",
    verificationStatus: "verified",
    themes: ["art", "patterns", "poetry"],
  },
  {
    id: "hardy-beauty-first-test",
    text: "Beauty is the first test: there is no permanent place in the world for ugly mathematics.",
    author: "G. H. Hardy",
    authorLifespan: "1877-1947",
    work: "A Mathematician's Apology",
    year: 1940,
    sourceUrl: "https://www.math.ualberta.ca/mss/misc/A%20Mathematician%27s%20Apology.pdf",
    sourceLabel: "A Mathematician's Apology PDF",
    sourceNote: "Strong but sharper in tone; best for beauty/aesthetic judgment rather than playful posts.",
    verificationStatus: "verified",
    themes: ["beauty", "proof"],
  },
  {
    id: "russell-mathematics-supreme-beauty",
    text: "Mathematics, rightly viewed, possesses not only truth, but supreme beauty.",
    author: "Bertrand Russell",
    authorLifespan: "1872-1970",
    work: "The Study of Mathematics",
    year: 1907,
    sourceUrl: "https://www.gutenberg.org/files/25447/25447-h/25447-h.htm",
    sourceLabel: "Project Gutenberg",
    sourceNote: "From Russell's essay collection Mysticism and Logic and Other Essays.",
    verificationStatus: "verified",
    themes: ["beauty", "proof"],
  },
  {
    id: "poincare-art-same-name",
    text: "Mathematics is the art of giving the same name to different things.",
    author: "Henri Poincare",
    authorLifespan: "1854-1912",
    work: "Science and Method",
    year: 1908,
    sourceUrl: "https://old.maa.org/press/periodicals/convergence/quotations-in-context-poincare",
    sourceLabel: "Mathematical Association of America",
    sourceNote: "Good for abstraction, metaphor, and the craft of noticing structure.",
    verificationStatus: "verified",
    themes: ["art", "patterns", "science"],
  },
  {
    id: "einstein-poetry-logical-ideas",
    text: "Pure mathematics is, in its way, the poetry of logical ideas.",
    author: "Albert Einstein",
    authorLifespan: "1879-1955",
    work: "Letter on Emmy Noether",
    year: 1935,
    sourceUrl: "https://mathshistory.st-andrews.ac.uk/Extras/Einstein_Emmy_Noether/",
    sourceLabel: "MacTutor History of Mathematics",
    sourceNote: "From Einstein's public letter after Emmy Noether's death.",
    verificationStatus: "verified",
    themes: ["logic", "poetry", "beauty"],
  },
  {
    id: "weyl-beautiful-and-true",
    text: "In my work I have always tried to unite the true with the beautiful; but when I had to choose one or the other, I usually chose the beautiful.",
    author: "Hermann Weyl",
    authorLifespan: "1885-1955",
    sourceUrl: "https://mathshistory.st-andrews.ac.uk/Biographies/Weyl/",
    sourceLabel: "MacTutor History of Mathematics",
    sourceNote: "Often cited from Weyl's reflections on mathematical physics; verify exact original context before formal publication.",
    verificationStatus: "secondary",
    themes: ["beauty", "science"],
  },
  {
    id: "dirac-beauty-equations",
    text: "It is more important to have beauty in one's equations than to have them fit experiment.",
    author: "Paul Dirac",
    authorLifespan: "1902-1984",
    work: "The Evolution of the Physicist's Picture of Nature",
    year: 1963,
    sourceUrl: "https://www.scientificamerican.com/article/the-evolution-of-the-physicists-pic/",
    sourceLabel: "Scientific American",
    sourceNote: "Physics-facing, but useful for the role of beauty in mathematical imagination.",
    verificationStatus: "verified",
    themes: ["beauty", "science"],
  },
  {
    id: "lockhart-mathematics-is-an-art",
    text: "The first thing to understand is that mathematics is an art.",
    author: "Paul Lockhart",
    work: "A Mathematician's Lament",
    year: 2002,
    sourceUrl: "https://www.maa.org/external_archive/devlin/LockhartsLament.pdf",
    sourceLabel: "Mathematical Association of America PDF",
    sourceNote: "Direct and teacher-friendly; useful for cards about learning mathematics as creative practice.",
    verificationStatus: "verified",
    themes: ["art", "play", "imagination"],
  },
  {
    id: "lockhart-art-of-explanation",
    text: "Mathematics is the art of explanation.",
    author: "Paul Lockhart",
    work: "A Mathematician's Lament",
    year: 2002,
    sourceUrl: "https://www.maa.org/external_archive/devlin/LockhartsLament.pdf",
    sourceLabel: "Mathematical Association of America PDF",
    sourceNote: "Compact and well-suited to social graphics.",
    verificationStatus: "verified",
    themes: ["art", "proof", "imagination"],
  },
  {
    id: "dyson-mathematics-art-not-science",
    text: "Mathematics is really an art, not a science.",
    author: "Freeman Dyson",
    authorLifespan: "1923-2020",
    sourceUrl: "https://quote.org/quote/mathematics-is-really-an-art-not-a-1726076",
    sourceLabel: "Quote.org",
    sourceNote: "Good candidate, but current citation is secondary; find the interview or original publication before publishing.",
    verificationStatus: "needs-review",
    themes: ["art", "science"],
  },
  {
    id: "knuth-science-art-computer",
    text: "Science is what we understand well enough to explain to a computer. Art is everything else we do.",
    author: "Donald Knuth",
    authorLifespan: "1938-",
    work: "Foreword to A = B",
    year: 1996,
    sourceUrl: "https://www2.math.upenn.edu/~wilf/AeqB.html",
    sourceLabel: "A = B",
    sourceNote: "Not specifically about mathematics, but apt for algorithms, creative problem solving, and the boundary between rigor and craft.",
    verificationStatus: "verified",
    themes: ["art", "science", "logic"],
  },
  {
    id: "devlin-science-of-patterns",
    text: "Mathematics is the science of patterns.",
    author: "Keith Devlin",
    work: "The Language of Mathematics",
    year: 1998,
    sourceUrl: "https://plus.maths.org/content/language-mathematics",
    sourceLabel: "Plus Magazine",
    sourceNote: "Concise framing for pattern-focused posts.",
    verificationStatus: "verified",
    themes: ["patterns", "science", "beauty"],
  },
  {
    id: "kovalevskaya-poet-in-soul",
    text: "It is impossible to be a mathematician without being a poet in soul.",
    author: "Sofia Kovalevskaya",
    authorLifespan: "1850-1891",
    sourceUrl: "https://mathshistory.st-andrews.ac.uk/Biographies/Kovalevskaya/",
    sourceLabel: "MacTutor History of Mathematics",
    sourceNote: "Widely attributed to Kovalevskaya; verify exact original wording and context before publishing.",
    verificationStatus: "secondary",
    themes: ["poetry", "imagination", "beauty"],
  },
];

export const verifiedMathArtQuotes = mathArtQuotes.filter(
  (quote) => quote.verificationStatus === "verified",
);
